### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by williamrbt08** [Erarnitox/TeraProxy#1]
Hi, sry for that but can u help me?

I'm trying to send packets in a game gta sa Multiplayer ( SA:MP )

I was able to intercept packets, but when i try to send them back the game crashes

I think its because i'm missing two arguments in stack

![help](https://user-images.githubusercontent.com/28076099/105669982-0f191a80-5ebf-11eb-8851-aa18cddc7c76.png)

How i add this 2 arguments to send a packet?

Thx

**Comment by Erarnitox** [comment]
Depends on the calling convention an what these arguments mean. But generally you just give them as arguments to the send function. 

So if the first parameter looks to be a pointer to the packet and the 2nd seems to be it's length.
then just add the other 2 parameters as well:

send(&packet, sizeof(packet), 1, 8); 

depending on the callkng convention you might want to reverse the order of the arguments.

Alternatively you can write a function call wrapper:

void sendWrapper(void* packet, int size){
    __asm{
        push 0x8
        push 0x1
    }
    send(packet, size);
}

You might want to look up the functions and function calls in Ghidra or Ida to be able to understand them better. 

Good Luck! :)

**Comment by williamrbt08** [comment]
Thx for the help :)
